spring:
  application:
    name: errorfreetext
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/errorfreetext}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

yandex:
  speller:
    endpoint: ${YANDEX_SPELLER_ENDPOINT:https://speller.yandex.net/services/spellservice.json/checkTexts}
    connect-timeout: ${YANDEX_SPELLER_CONNECT_TIMEOUT:3s}
    read-timeout: ${YANDEX_SPELLER_READ_TIMEOUT:10s}
